---
- name: create directory
  file:
    path: /home/cassandra/.ssh
    state: directory
    owner: cassandra
    group: cassandra
    mode: 0700

- name: copy public_key
  template: src=authorized_keys dest=/home/cassandra/.ssh mode=0400 owner=cassandra group=cassandra

- name: Create directories & change permission on existing directories
  file:
    path: "{{ item }}"
    state: directory
    owner: cassandra
    group: cassandra
    mode: 0755
    recurse: yes
  with_items:
     - /apps
     - /data1
     - /backup
     - /var/lib/cassandra
  changed_when: False
