---
- hosts: first-node 
  become: yes
  roles:
    - 0-server_connector
    - prerequisite
    - install-cassandra 

      #- hosts: nodes
      #become: yes
      #roles:
      #- prerequisite
      #- cassandra-nodes
